# Generated by Django 4.0.4 on 2022-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MEN'), ('F', 'WOME')], default='MEN', max_length=1, null=True),
        ),
    ]
