# Generated by Django 4.0.4 on 2022-05-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
